export interface  onboardSchoolData {
    name: string,
    type: string,
    county: string,
    subcounty: string,
    ward: string,
    county_code?: string,
    address: string,
    phone_number: string,
    location: string,
    email: string,
    status: string,
    total_students: number,
    total_teachers: number,
    boarding_type: string,
    gender_based: string,
    // created_by: number,
};